plugins {
    id 'net.fabricmc.fabric-loom' version '0.10.73'
    id 'maven-publish'
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = "ekatys"
version = "1.0.0"
group = "com.example"

repositories {
    maven { url "https://maven.fabricmc.net/" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.16.5"
    mappings "net.fabricmc:yarn:1.16.5+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.11.3"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.36.0+1.16.5"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 16
}
