plugins {
    id 'net.fabricmc.fabric-loom' version '1.7-SNAPSHOT' 
    id 'maven-publish'
}

sourceCompatibility = JavaVersion.VERSION_17 // Gradle 9 требует минимум 17 для себя
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

repositories {
    maven { url "https://maven.fabricmc.net/" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.16.5"
    mappings "net.fabricmc:yarn:1.16.5+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

// Это чтобы майнкрафт 1.16.5 не офигел от новой явы
tasks.withType(JavaCompile).configureEach {
    it.options.release = 16 
}
