# Память для сборки
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Версии для Майнкрафт 1.16.5
minecraft_version=1.16.5
# Самые стабильные маппинги для этой версии
yarn_mappings=1.16.5+build.1
loader_version=0.11.3
loom_version=0.10-SNAPSHOT

# Свойства твоего мода
mod_version=1.0.0
maven_group=com.example
archives_base_name=modid

# Fabric API именно для 1.16.5
fabric_api_version=0.36.0+1.16
